config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :people
  resources :envelope_formulas, except: [:show]
  resources :profits, except: [:show]
  devise_for :users, skip: %i[password registrations sessions], controllers: {
    sessions: 'users/sessions'
  }
  as :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :galleries
  resources :users

  get '/partners/:id', to: 'partners#partner_gallery', as: 'partner_gallery'
  get '/favorites', to: 'galleries#favorites', as: 'favorites'
  get '/candidates', to: 'partners#candidates'
  get '/partners', to: 'partners#index'
  post '/partners/new_request', to: 'partners#new_request'
  post '/partners/approve_or_deny_request', to: 'partners#approve_or_deny_request'
  post '/partners/remove_request', to: 'partners#remove_request'
end

app/models/envelope_formula.rb
# == Schema Information
#
# Table name: envelope_formulas
#
#  id                           :bigint           not null, primary key
#  daily_expences               :decimal(10, 2)   not null
#  funds_for_expensive_purchase :decimal(10, 2)   not null
#  funds_for_others             :decimal(10, 2)   not null
#  funds_for_self_development   :decimal(10, 2)   not null
#  investment_funds             :decimal(10, 2)   not null
#  name                         :string           not null
#  savings                      :decimal(10, 2)   not null
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  user_id                      :bigint           not null
#
# Indexes
#
#  index_envelope_formulas_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class EnvelopeFormula < ApplicationRecord
  belongs_to :user
  has_many :profits, dependent: :restrict_with_exception

  scope :ordered, ->{ order(:name) }

  validates :name, :daily_expences, :funds_for_expensive_purchase, :funds_for_others,
            :funds_for_self_development, :investment_funds, :savings, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  # add custom validation for only 100% sum of all fields
end

app/controllers/envelope_formulas_controller.rb
class EnvelopeFormulasController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :ensure_frame_response, only: [:new, :edit]

  def index
    @envelope_formulas = collection
  end

  def new
    @envelope_formula = EnvelopeFormula.new
  end

  def edit
    @envelope_formula = resource
  end

  def create
    @envelope_formula = current_user.envelope_formulas.new(envelope_formula_params)

    if @envelope_formula.save
      render turbo_stream: [
        turbo_stream.after('new-envelope_formula-form', @envelope_formula),
        turbo_stream.replace('form_envelope_formula', '')
      ]
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @envelope_formula = resource

    if @envelope_formula.update(envelope_formula_params)
      render @envelope_formula
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @envelope_formula = resource

    @envelope_formula.destroy

    render turbo_stream: [
      turbo_stream.remove(@envelope_formula)
    ]
  end

  private

    def collection
      EnvelopeFormula.ordered
    end

    def resource
      collection.find(params[:id])
    end

    def envelope_formula_params
      params.require(:envelope_formula).permit(:name, :daily_expences, :savings,
                                              :funds_for_expensive_purchase, :funds_for_others,
                                              :funds_for_self_development, :investment_funds)
    end

    def ensure_frame_response
      redirect_to root_path unless turbo_frame_request?
    end
end

app/helpers/envelope_formula_helper.rb
module EnvelopeFormulaHelper
  def options_with_data(collection)
    collection.map do |record|
      data_attributes = {}

      [:daily_expences, :funds_for_expensive_purchase, :funds_for_others,
      :funds_for_self_development, :investment_funds, :savings].each do |field|
        data_attributes.merge!(field => record.send(field))
      end

      [record.name, record.id, { data: data_attributes }]
    end
  end
end

app/views/envelope_formulas/_envelope_formula.html.erb
<%= turbo_frame_tag envelope_formula, class: 'text-gray-700 grid grid-cols-9 dark:text-gray-400 divide-y dark:divide-gray-700' do %>
  <div class="flex items-center col-span-2 px-4 py-3 text-xs border-t dark:border-gray-700"><%= envelope_formula.name %></div>
  <div class="flex items-center px-4 py-3 text-xs"><%= number_to_percentage(envelope_formula.daily_expences * 100, precision: 1) %></div>
  <div class="flex items-center px-4 py-3 text-xs"><%= number_to_percentage(envelope_formula.savings * 100, precision: 1) %></div>
  <div class="flex items-center px-4 py-3 text-xs"><%= number_to_percentage(envelope_formula.funds_for_others * 100, precision: 1) %></div>
  <div class="flex items-center px-4 py-3 text-xs"><%= number_to_percentage(envelope_formula.funds_for_self_development * 100, precision: 1) %></div>
  <div class="flex items-center px-4 py-3 text-xs"><%= number_to_percentage(envelope_formula.funds_for_expensive_purchase * 100, precision: 1) %></div>
  <div class="flex items-center px-4 py-3 text-xs"><%= number_to_percentage(envelope_formula.investment_funds * 100, precision: 1) %></div>
  <div class="flex items-center gap-3 px-4 py-3 text-xs text-red-500">
    <%= button_to edit_envelope_formula_path(envelope_formula), method: :get, class: 'flex w-fit items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-full active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple', aria_label: 'edit' do %>
      <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
        <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
      </svg>
    <% end %>
    <%= button_to envelope_formula_path(envelope_formula), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }  do %>
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
    <% end %>
  </div>
<% end %>

app/views/envelope_formulas/_form.html.erb
<%= form_with model: envelope_formula, id: dom_id(envelope_formula, "form"), class: "text-gray-900 col-span-9 dark:text-gray-800 grid grid-cols-9" do |form| %>
  <div class="col-span-2 px-4 py-3 text-xs">
    <%= form.text_field :name, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 w-full" %>
    <%= inline_error_for(:name, envelope_formula) %>
  </div>
  <div class="px-4 py-3 text-xs">
    <%= form.text_field :daily_expences, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 w-full", placeholder: '0.2' %>
    <%= inline_error_for(:daily_expences, envelope_formula) %>
  </div>
  <div class="px-4 py-3 text-xs">
    <%= form.text_field :savings, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 w-full", placeholder: '0.2' %>
    <%= inline_error_for(:savings, envelope_formula) %>
  </div>
  <div class="px-4 py-3 text-xs">
    <%= form.text_field :funds_for_others, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 w-full", placeholder: '0.2' %>
    <%= inline_error_for(:funds_for_others, envelope_formula) %>
  </div>
  <div class="px-4 py-3 text-xs">
    <%= form.text_field :funds_for_self_development, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 w-full", placeholder: '0.2' %>
    <%= inline_error_for(:funds_for_self_development, envelope_formula) %>
  </div>
  <div class="px-4 py-3 text-xs">
    <%= form.text_field :funds_for_expensive_purchase, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 w-full", placeholder: '0.2' %>
    <%= inline_error_for(:funds_for_expensive_purchase, envelope_formula) %>
  </div>
  <div class="px-4 py-3 text-xs">
    <%= form.text_field :investment_funds, class: "block rounded-md border border-gray-200 outline-none px-3 py-2 w-full", placeholder: '0.2' %>
    <%= inline_error_for(:investment_funds, envelope_formula) %>
  </div>
  <div class="flex items-center gap-3 px-4 py-3 text-xs w-fit">
    <%= button_tag type: 'submit', class: 'flex w-fit items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-blue-600 border border-transparent rounded-full active:bg-blue-600 hover:bg-blue-700 focus:outline-none focus:shadow-outline-blue', aria_label: 'submit' do %>
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
    <% end %>
    <% if params[:action] != 'edit' %>
      <%= button_tag type: 'button', data: { action: 'click->clear-frame#clear' }, class: 'text-xs text-red-500'  do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/envelope_formulas/edit.html.erb
<%= turbo_frame_tag @envelope_formula, class: 'text-gray-700 dark:text-gray-400' do %>
  <%= render 'form', envelope_formula: @envelope_formula %>
<% end %>

app/views/envelope_formulas/index.html.erb
<section>
  <div class="flex flex-col justify-between gap-5 mb-5 sm:flex-row">
    <h1 class="text-4xl font-bold text-dark-grey dark:text-white">Envelope formulas</h1>
    <%= button_to 'New envelope formula', new_envelope_formula_path, class: "btn-blue w-full sm:w-fit", method: :get, data: { turbo_frame: 'new-envelope_formula-form' } %>
  </div>
  <div class="w-full overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <div class="grid w-full whitespace-no-wrap shadow-lg">
        <div class="">
          <div class="grid grid-cols-9 text-xs font-semibold tracking-wide text-left text-gray-500 uppercase bg-gray-100 border-b tableNew dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800"> <%# thead %>
            <div class="flex items-center col-span-2 px-4 py-3">Name</div>
            <div class="flex items-center px-4 py-3">Daily expences</div>
            <div class="flex items-center px-4 py-3">Savings</div>
            <div class="flex items-center px-4 py-3">For others</div>
            <div class="flex items-center px-4 py-3">For self development</div>
            <div class="flex items-center px-4 py-3">For expensive purchase</div>
            <div class="flex items-center px-4 py-3">Investment funds</div>
            <div class="flex items-center px-4 py-3">&nbsp;</div>
          </div>
        </div>
        <div id="envelope_formulas" class="bg-white dark:bg-gray-800">
          <%= turbo_frame_tag 'new-envelope_formula-form', data: { controller: 'clear-frame' } %>
          <%= render @envelope_formulas%>
        </div>
      </div>
  </div>
</section>

app/views/envelope_formulas/new.html.erb
<%= turbo_frame_tag "new-envelope_formula-form" do %>
  <%= render "envelope_formulas/form", envelope_formula: @envelope_formula %>
<% end %>