config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :people
  resources :envelope_formulas, except: [:show]
  resources :profits, except: [:show]
  devise_for :users, skip: %i[password registrations sessions], controllers: {
    sessions: 'users/sessions'
  }
  as :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :galleries
  resources :users

  get '/partners/:id', to: 'partners#partner_gallery', as: 'partner_gallery'
  get '/favorites', to: 'galleries#favorites', as: 'favorites'
  get '/candidates', to: 'partners#candidates'
  get '/partners', to: 'partners#index'
  post '/partners/new_request', to: 'partners#new_request'
  post '/partners/approve_or_deny_request', to: 'partners#approve_or_deny_request'
  post '/partners/remove_request', to: 'partners#remove_request'
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id                 :bigint           not null, primary key
#  birthday           :datetime
#  blue_personality   :decimal(10, 2)   default(0.0)
#  characteristic     :text
#  email              :string
#  first_name         :string
#  gender             :integer
#  green_personality  :decimal(10, 2)   default(0.0)
#  instagram_url      :string
#  last_name          :string
#  phone_number       :bigint
#  photo              :string           not null
#  red_personality    :decimal(10, 2)   default(0.0)
#  second_name        :string
#  telegram           :string
#  yellow_personality :decimal(10, 2)   default(0.0)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  childhood_city_id  :bigint
#  current_city_id    :bigint           not null
#
# Indexes
#
#  index_people_on_childhood_city_id  (childhood_city_id)
#  index_people_on_current_city_id    (current_city_id)
#
# Foreign Keys
#
#  fk_rails_...  (childhood_city_id => cities.id)
#  fk_rails_...  (current_city_id => cities.id)
#
class Person < ApplicationRecord
  GENDERS = { man: 0, woman: 1 }.freeze

  enum gender: GENDERS

  mount_uploader :photo, PersonPhotoUploader

  belongs_to :childhood_city, class_name: 'City', optional: true
  belongs_to :current_city, class_name: 'City'

  validates :first_name, :gender, :photo, presence: true
  validates :gender, inclusion: { in: HashWithIndifferentAccess.new(GENDERS).keys }

  scope :ordered, ->{ order(:first_name) }
  after_initialize :set_default_picture

  def full_name
    "#{first_name} #{last_name} #{second_name}"
  end

  def set_default_picture
    return if self.photo.present?

    self.photo = FakePicture::Avatar.file(gender&.to_sym || GENDERS.keys.sample)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]

  def index
    @q = Person.ransack(params[:q])
    @people = @q.result.includes(:childhood_city, :current_city).ordered
  end

  def show; end

  def new
    @person = Person.new
  end

  def edit; end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path, notice: 'Person was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @person.update(person_params)
      redirect_to people_path, notice: 'Person was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @person.destroy

    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:first_name, :second_name, :last_name, :photo,
                                    :phone_number, :email, :birthday, :gender,
                                    :childhook_city_id, :current_city_id, :characteristic,
                                    :blue_personality, :red_personality, :green_personality,
                                    :yellow_personality, :instagram_url, :telegram,
                                    :photo_cache)
  end
end

app/views/people/_form.html.erb
<%= simple_form_for person, html: { data: {
                                            controller: 'form',
                                            form_file_field_selector_value: '#person_photo',
                                            form_picture_container_selector_value: 'label[for="person_photo"]'
                                          } } do |f| %>
  <label class="relative block w-40 h-40 mx-auto mb-10 overflow-hidden bg-white bg-center bg-cover rounded-full cursor-pointer avatar-picture"
                for="person_photo" style="background-image: url(<%= f.object.photo&.url %>)">
    <span class="absolute font-bold">Upload</span>
    <div class="overlay"></div>
  </label>
  <%= f.input :photo, label: false, input_html: { class: 'hidden', data: { action: 'change->form#handlePictureUpload' } } %>
  <%= f.input :photo_cache, as: :hidden %>

  <div class="grid grid-cols-1 gap-5 xl:grid-cols-2">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
  </div>

  <div class="grid grid-cols-1 gap-5 xl:grid-cols-2">
    <%= f.input :instagram_url %>
    <%= f.input :telegram %>
  </div>

  <%= f.input :gender, collection: Person::GENDERS.keys %>
  <%= f.association :current_city, collection: City.ordered %>

  <%= f.input :characteristic %>

  <%= f.button :submit %>
<% end %>

app/views/people/_search_form.html.erb
<%= search_form_for q do |f| %>
  <div class="inline-block">
    <%= f.label :gender_eq, 'Filter by gender - ', class: 'hidden lg:inline' %>
    <%= f.select :gender_eq, Person::GENDERS, { include_blank: 'All' }, { onchange: 'this.form.submit()', class: 'input mr-2' } %>

    <%= f.label :current_city_id_eq, 'Filter by current city - ', class: 'hidden lg:inline' %>
    <%= f.select :current_city_id_eq, City.with_people_for_current_city.ordered.pluck(:name, :id), { include_blank: City.with_people_for_current_city.any? ? 'All' : 'Nothing' }, { onchange: 'this.form.submit()', class: 'input mr-2' } %>

    <%= f.label :childhood_city_id_eq, 'Filter by childhood city - ', class: 'hidden lg:inline' %>
    <%= f.select :childhood_city_id_eq, City.with_people_for_childhood_city.ordered.pluck(:name, :id), { include_blank: City.with_people_for_childhood_city.any? ? 'All' : 'Nothing' }, { onchange: 'this.form.submit()', class: 'input mr-2' } %>
  </div>
<% end %>

app/views/people/edit.html.erb
<section class="w-full h-full mx-auto md:w-2/3">
  <%= link_to people_path, class: 'text-gray-800 dark:text-gray-200 flex gap-1 absolute top-10 left-12' do %>
    <%= inline_svg_tag 'icons/arrow-left.svg' %>
    <span>Back</span>
  <% end %>
  <%= render 'people/form', person: @person %>
</section>

app/views/people/index.html.erb
<section class="h-full">
  <div class="w-full px-5 py-3 my-5 mb-4 bg-white rounded-md shadow-md dark:bg-gray-800 text-light-grey dark:text-white">
    <%= render 'people/search_form', q: @q %>
  </div>
  <div class="flex flex-wrap">
    <% @people.each do |person| %>
      <div class="w-full p-2 sm:w-1/2 xl:w-1/3">
        <div class="relative flex-col w-full text-gray-900 dark:text-white card">
          <%= link_to edit_person_path(person), class: 'absolute left-7 top-4 hover:underline text-gray-600 hover:text-gray-400' do %>
            <span>Edit</span>
          <% end %>
          <%= image_tag person.photo.url, width: 160, height: 160, class: 'rounded-full block mx-auto mb-5 h-40 w-40 object-cover' %>
          <%= simple_format(person.full_name) %>

          <div class="flex items-center justify-between w-full">
            <div class="flex flex-col w-full px-5 mt-10 mb-5">
              <div class="flex gap-2">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
                <%= simple_format(person.current_city.name) %>
              </div>
              <%= simple_format(person.birthday&.strftime("%d.%m.%Y")) %>
            </div>
            <div class="flex flex-col gap-1">
              <% if person.telegram? %>
                <%= link_to "https://t.me/#{person.telegram}", target: :_blank do %>
                  <%= image_tag 'icons/telegram.svg' %>
                <% end %>
              <% end %>
              <% if person.instagram_url? %>
                <%= link_to person.instagram_url, target: :_blank do %>
                  <%= image_tag 'icons/instagram.svg' %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/people/new.html.erb
<section class="w-full h-full mx-auto md:w-2/3">
  <%= render 'people/form', person: @person %>
</section>