config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :people
  resources :envelope_formulas, except: [:show]
  resources :profits, except: [:show]
  devise_for :users, skip: %i[password registrations sessions], controllers: {
    sessions: 'users/sessions'
  }
  as :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :galleries
  resources :users

  get '/partners/:id', to: 'partners#partner_gallery', as: 'partner_gallery'
  get '/favorites', to: 'galleries#favorites', as: 'favorites'
  get '/candidates', to: 'partners#candidates'
  get '/partners', to: 'partners#index'
  post '/partners/new_request', to: 'partners#new_request'
  post '/partners/approve_or_deny_request', to: 'partners#approve_or_deny_request'
  post '/partners/remove_request', to: 'partners#remove_request'
end

app/views/shared/_logo.html.erb
<svg class="css-g5ufxp" id="gdhffcce"<% _slim_codeattributes1 = ("xMidYMid meet"); if _slim_codeattributes1; if _slim_codeattributes1 == true %> preserveaspectratio=""<% else %> preserveaspectratio="<%= _slim_codeattributes1 %>"<% end; end; _slim_codeattributes2 = ("0 0 369.68224299065423 119.78626567397313"); if _slim_codeattributes2; if _slim_codeattributes2 == true %> viewbox=""<% else %> viewbox="<%= _slim_codeattributes2 %>"<% end; end %>>
  <defs id="SvgjsDefs1082">
    <lineargradient id="SvgjsLinearGradient1089">
      <stop id="SvgjsStop1090" offset="0" stop-color="#8f5e25">
      </stop>
      <stop id="SvgjsStop1091" offset="0.5" stop-color="#fbf4a1">
      </stop>
      <stop id="SvgjsStop1092" offset="1" stop-color="#8f5e25">
      </stop>
    </lineargradient>
    <lineargradient id="SvgjsLinearGradient1093">
      <stop id="SvgjsStop1094" offset="0" stop-color="#8f5e25">
      </stop>
      <stop id="SvgjsStop1095" offset="0.5" stop-color="#fbf4a1">
      </stop>
      <stop id="SvgjsStop1096" offset="1" stop-color="#8f5e25">
      </stop>
    </lineargradient>
    <lineargradient id="SvgjsLinearGradient1097">
      <stop id="SvgjsStop1098" offset="0" stop-color="#8f5e25">
      </stop>
      <stop id="SvgjsStop1099" offset="0.5" stop-color="#fbf4a1">
      </stop>
      <stop id="SvgjsStop1100" offset="1" stop-color="#8f5e25">
      </stop>
    </lineargradient>
  </defs>
  <g featurekey="symbolFeature-0" fill="currentColor" id="SvgjsG1083" transform="matrix(1.254743099443719,0,0,1.254743099443719,-18.57898127449468,-2.2740290106807137)">
    <path d="M85.023,43.02c0.005-0.008,0.01-0.017,0.014-0.025c0.008-0.015,0.016-0.029,0.023-0.044  c0.004-0.007,0.007-0.014,0.011-0.022c0.009-0.019,0.018-0.039,0.026-0.058c0.001-0.003,0.003-0.006,0.004-0.009  c0.02-0.05,0.037-0.1,0.051-0.151c0.001-0.002,0.001-0.005,0.002-0.007c0.007-0.025,0.012-0.05,0.017-0.075  c0-0.001,0-0.002,0.001-0.003c0.01-0.053,0.017-0.106,0.021-0.159c0-0.005,0.001-0.01,0.001-0.014  c0.001-0.022-0.005-0.044-0.005-0.066c0-0.004-0.007-0.007-0.007-0.01V26.283c0-0.454-0.232-0.874-0.624-1.104L50.656,5.178  c-0.401-0.237-0.9-0.237-1.3,0l-33.912,20c-0.391,0.23-0.637,0.65-0.637,1.104v16.094c0,0.003,0.008,0.007,0.008,0.01  c0,0.022,0.005,0.044,0.006,0.066c0,0.005,0.002,0.01,0.003,0.014c0.004,0.053,0.012,0.106,0.022,0.159  c0,0.001,0.001,0.002,0.001,0.003c0.005,0.025,0.011,0.05,0.018,0.075c0.001,0.002,0.001,0.005,0.002,0.007  c0.014,0.051,0.031,0.101,0.051,0.151c0.001,0.003,0.003,0.006,0.004,0.009c0.008,0.019,0.017,0.039,0.026,0.058  c0.003,0.007,0.007,0.014,0.011,0.022c0.007,0.015,0.015,0.029,0.023,0.044c0.005,0.009,0.009,0.017,0.014,0.025  c0.008,0.014,0.017,0.028,0.026,0.042c0.005,0.008,0.01,0.017,0.016,0.025l33.903,51.337c0.238,0.36,0.639,0.576,1.07,0.576  c0.431,0,0.832-0.216,1.07-0.576l33.903-51.337c0.006-0.008,0.01-0.017,0.016-0.025C85.006,43.048,85.015,43.034,85.023,43.02z   M17.374,27.014L50.011,7.77l32.637,19.245v14.629L50.011,60.889L17.374,41.644V27.014z M20.225,46.299l28.924,17.062v26.736  L20.225,46.299z M50.874,90.097V63.361l28.924-17.062L50.874,90.097z" xmlns="http://www.w3.org/2000/svg">
    </path>
  </g>
  <g featurekey="nameFeature-0" fill="currentColor" id="SvgjsG1084" transform="matrix(1.9056381374406033,0,0,1.9056381374406033,99.61519201352553,-19.36127955090293)">
    <path<% _slim_codeattributes3 = ("M8.72 26.8 l0 13.2 l-4.32 0 l0 -29.84 l4.32 0 l0 12.24 q1.6 -0.8 3.8 -0.8 q0.8 0 3.88 0.36 q4.32 0.52 5.84 0.52 q2.32 0 4.04 -0.76 l0 -11.56 l4.36 0 l0 29.84 l-4.36 0 l0 -13.88 q-1.72 0.76 -4.04 0.76 q-1.52 0 -5.84 -0.52 q-3.08 -0.36 -3.88 -0.36 q-2.2 0 -3.8 0.8 z M52.44 40.68 q-4.2 0 -7.22 -1.46 t-4.6 -4.22 t-1.58 -6.6 l0 -18.24 l4.32 0 l0 18.24 q0 3.84 2.36 5.88 t6.72 2.04 t6.72 -2.04 t2.36 -5.88 l0 -18.24 l4.32 0 l0 18.24 q0 3.84 -1.58 6.6 t-4.6 4.22 t-7.22 1.46 z M75.12 14.36 l-3.48 -4.2 l5.64 0 l19.16 22.8 l0 -22.8 l4.4 0 l0 29.84 l-4.32 0 l-17.12 -20.52 l0 20.52 l-4.28 0 l0 -25.64 z M131.84 14.559999999999999 l-10.52 0 l0 25.44 l-4.24 0 l0 -25.44 l-10.64 0 l0 -4.4 l25.4 0 l0 4.4 z M141.72000000000003 40 l-4.28 0 l0 -29.84 l4.28 0 l0 29.84 z"); if _slim_codeattributes3; if _slim_codeattributes3 == true %> d=""<% else %> d="<%= _slim_codeattributes3 %>"<% end; end %>>
    </path>
  </g>
  <g featurekey="nameFeature-1" fill="currentColor" id="SvgjsG1085" transform="matrix(1.6441457462277747,0,0,1.6441457462277747,104.05404887627071,52.742329482020104)">
    <path<% _slim_codeattributes4 = ("M29.96 14 l-2.8 3.28 q-1.64 -1.68 -3.92 -2.64 t-4.8 -0.96 q-3.28 0 -5.98 1.48 t-4.22 4.04 q-1.56 2.68 -1.56 5.96 q0 3.12 1.68 5.76 q1.6 2.48 4.3 3.94 t5.82 1.46 q2.88 0 5.36 -1.24 t4.12 -3.44 l2.68 3.64 q-2.28 2.56 -5.46 3.98 t-6.74 1.42 q-4.44 0 -8.16 -2.16 q-3.64 -2.08 -5.72 -5.72 q-2.16 -3.72 -2.16 -8.16 q0 -4.28 2.28 -7.88 q2.16 -3.44 5.86 -5.46 t7.94 -2.02 q3.32 0 6.32 1.28 q2.92 1.2 5.16 3.44 z M57.96 40 l-20.92 0 l0 -29.84 l4.36 0 l0 25.48 l16.56 0 l0 4.36 z M88.96000000000001 24.880000000000003 q0 -3.2 -1.64 -5.8 q-1.56 -2.52 -4.26 -3.96 t-5.86 -1.44 q-3.28 0 -5.98 1.48 t-4.22 4.04 q-1.56 2.68 -1.56 5.96 q0 3.12 1.68 5.76 q1.6 2.48 4.3 3.94 t5.84 1.46 t5.84 -1.52 t4.26 -4.08 q1.6 -2.68 1.6 -5.84 z M93.28 25.119999999999997 q0 4.32 -2.24 7.96 q-2.16 3.48 -5.86 5.54 t-7.98 2.06 q-4.44 0 -8.16 -2.16 q-3.64 -2.08 -5.72 -5.72 q-2.16 -3.72 -2.16 -8.16 q0 -4.28 2.28 -7.88 q2.16 -3.44 5.86 -5.46 t7.94 -2.02 q4.36 0 8.08 2.12 q3.64 2.08 5.76 5.64 q2.2 3.72 2.2 8.08 z M113.08000000000001 40.68 q-4.2 0 -7.22 -1.46 t-4.6 -4.22 t-1.58 -6.6 l0 -18.24 l4.32 0 l0 18.24 q0 3.84 2.36 5.88 t6.72 2.04 t6.72 -2.04 t2.36 -5.88 l0 -18.24 l4.32 0 l0 18.24 q0 3.84 -1.58 6.6 t-4.6 4.22 t-7.22 1.46 z M140.84000000000003 14.559999999999999 l0 21.08 l6.76 0 q2.8 0 5.04 -1.44 q2.12 -1.4 3.32 -3.76 t1.2 -5.16 q0 -2.92 -1.14 -5.36 t-3.26 -3.88 q-2.28 -1.48 -5.24 -1.48 l-6.68 0 z M134.20000000000002 14.559999999999999 l-1.92 -4.4 l15.2 0 q3.96 0 7.24 2.04 q3.16 1.96 5 5.36 t1.84 7.4 q0 3 -1.18 5.94 t-3.26 5.14 q-2 2.16 -4.28 3.08 q-2.2 0.88 -5.24 0.88 l-11.04 0 l0 -25.44 l-2.36 0 z"); if _slim_codeattributes4; if _slim_codeattributes4 == true %> d=""<% else %> d="<%= _slim_codeattributes4 %>"<% end; end %>>
    </path>
  </g>
</svg>

app/views/shared/_navbar.html.erb
<header class="z-10 py-4 bg-white shadow-md dark:bg-light-grey" data-controller="dropdown dark-theme">
  <div class="container flex items-center justify-between h-full px-6 mx-auto text-purple-600 dark:text-purple-300">
    <!-- Mobile hamburger -->
    <button class="p-1 mr-5 -ml-1 rounded-md xl:hidden focus:outline-none focus:shadow-outline-purple" data-action="click->menu#toggleMenu focusout->menu#hide">
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path>
      </svg>
    </button>
    <!-- Search input -->
    <div class="flex justify-center flex-1 lg:mr-32">
      <div class="relative w-full max-w-xl mr-6 focus-within:text-purple-500">
        <div class="absolute inset-y-0 flex items-center pl-2">
          <svg class="w-4 h-4" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
          </svg>
        </div>
        <input class="w-full pl-8 pr-2 text-sm text-gray-700 placeholder-gray-600 bg-gray-100 border-0 rounded-md dark:placeholder-gray-500 dark:focus:shadow-outline-gray dark:focus:placeholder-gray-600 dark:bg-gray-700 dark:text-gray-200 focus:placeholder-gray-500 focus:bg-white focus:border-purple-300 focus:outline-none focus:shadow-outline-purple form-input" type="text" placeholder="Search for projects" aria-label="Search">
      </div>
    </div>
    <ul class="flex items-center flex-shrink-0 space-x-6">
      <!-- Theme toggler -->
      <li class="flex">
        <button class="rounded-md focus:outline-none focus:shadow-outline-purple" data-action="click->dark-theme#toggleTheme">
          <svg class="<%= 'hidden' if cookies[:dark_theme] == 'true' %> w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" data-dark-theme-target="moon">
            <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path>
          </svg>
          <svg class="<%= 'hidden' if cookies[:dark_theme] != 'true' %> w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" data-dark-theme-target="sun">
            <path fill-rule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" clip-rule="evenodd"></path>
          </svg>
        </button>
      </li>
      <% if current_user.present? %>
        <!-- Profile menu -->
        <li class="relative">
          <button class="align-middle rounded-full focus:shadow-outline-purple focus:outline-none" data-action="click->dropdown#toggleMenu">
            <%= image_tag Avatarro.image(current_user.full_name, random: true, solid: true), size: '20x20', class: 'object-cover w-8 h-8 rounded-full' %>
          </button>
          <ul class="absolute right-0 hidden w-56 p-2 mt-2 space-y-2 text-gray-600 transition delay-150 bg-white border border-gray-100 rounded-md shadow-md opacity-0 dark:border-gray-700 dark:text-gray-300 dark:bg-gray-700" data-dropdown-target="menu">
            <%# <li class="flex">
              <a class="inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200" href="#">
                <svg class="w-4 h-4 mr-3" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                  <path d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
                  <path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                </svg>
                <span>Settings</span>
              </a>
            </li> %>
            <li class="flex">
              <%= button_to destroy_user_session_path, method: :delete, form_class: 'w-full', class: 'inline-flex items-center w-full px-2 py-1 text-sm font-semibold transition-colors duration-150 rounded-md hover:bg-gray-100 hover:text-gray-800 dark:hover:bg-gray-800 dark:hover:text-gray-200' do %>
                <svg class="w-4 h-4 mr-3" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                  <path d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"></path>
                </svg>
                <span>Log out</span>
              <% end %>
            </li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_sidebar.html.erb
<!-- Desktop sidebar -->
<aside class="z-20 flex-shrink-0 hidden w-64 overflow-y-auto bg-white dark:bg-light-grey xl:block">
  <div class="py-4 text-gray-500 dark:text-gray-400">
    <%= link_to root_path do %>
      <div class="mt-4 mx-centered-logo w-36 text-dark-grey dark:text-white">
        <%= render 'shared/logo' %>
      </div>
    <% end %>

    <ul class="mt-10 text-gray-500 dark:text-gray-400">
      <% [:gallery, :people, :envelope_formulas, :profits].each do |controller_name| %>
        <% path = send("#{controller_name.to_s.pluralize}_path") %>
        <li class="relative px-6 py-3">
          <%= '<span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>'.html_safe if current_page?(path) %>
          <%= link_to path, class: "inline-flex items-center w-full text-sm font-semibold #{'text-gray-800 dark:text-gray-100' if current_page?(path)} transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" do %>
            <%= svg_for(controller_name) %>
            <span class="ml-4"><%= controller_name.to_s.humanize %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="flex flex-col gap-3 px-6 my-6">
      <%= link_to new_person_path, class: 'flex items-center justify-between w-full px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple' do %>
        Create person
        <span class="ml-2" aria-hidden="true">+</span>
      <% end %>
      <%= link_to new_profit_path, class: 'flex items-center justify-between w-full px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-amber-600 border border-transparent rounded-lg active:bg-amber-600 hover:bg-amber-700 focus:outline-none focus:shadow-outline-amber' do %>
        Add profit
        <span class="ml-2" aria-hidden="true">+</span>
      <% end %>
    </div>
  </div>
</aside>
<!-- Mobile sidebar -->
<!-- Backdrop -->
<div class="fixed inset-0 z-10 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center" style="display: none;" data-menu-target="backdrop"></div>
<aside class="fixed inset-y-0 z-20 flex-shrink-0 w-64 mt-16 overflow-y-auto bg-white dark:bg-light-grey xl:hidden" style="display: none;" data-menu-target="sidebar">
  <div class="py-4 text-gray-500 dark:text-gray-400">
    <div class="px-6 my-6">
      <button class="flex items-center justify-between w-full px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
        Create person
        <span class="ml-2" aria-hidden="true">+</span>
      </button>
    </div>
  </div>
</aside>