config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :people
  resources :envelope_formulas, except: [:show]
  resources :profits, except: [:show]
  devise_for :users, skip: %i[password registrations sessions], controllers: {
    sessions: 'users/sessions'
  }
  as :user do
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  resources :galleries
  resources :users

  get '/partners/:id', to: 'partners#partner_gallery', as: 'partner_gallery'
  get '/favorites', to: 'galleries#favorites', as: 'favorites'
  get '/candidates', to: 'partners#candidates'
  get '/partners', to: 'partners#index'
  post '/partners/new_request', to: 'partners#new_request'
  post '/partners/approve_or_deny_request', to: 'partners#approve_or_deny_request'
  post '/partners/remove_request', to: 'partners#remove_request'
end

app/models/profit.rb
# == Schema Information
#
# Table name: profits
#
#  id                           :bigint           not null, primary key
#  amount                       :decimal(, )      not null
#  daily_expences               :decimal(, )
#  funds_for_expensive_purchase :decimal(, )
#  funds_for_others             :decimal(, )
#  funds_for_self_development   :decimal(, )
#  investment_funds             :decimal(, )
#  savings                      :decimal(, )
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  envelope_formula_id          :bigint
#  user_id                      :bigint           not null
#
# Indexes
#
#  index_profits_on_envelope_formula_id  (envelope_formula_id)
#  index_profits_on_user_id              (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (envelope_formula_id => envelope_formulas.id)
#  fk_rails_...  (user_id => users.id)
#
class Profit < ApplicationRecord
  belongs_to :user
  belongs_to :envelope_formula

  scope :ordered, ->{ order(created_at: :desc) }

  validates :amount, presence: true
end

app/controllers/profits_controller.rb
class ProfitsController < ApplicationController
  before_action :set_profit, only: %i[ show edit update destroy ]

  def index
    @profits = Profit.ordered
  end

  def new
    @profit = Profit.new
  end

  def edit
  end

  def create
    @profit = current_user.profits.new(profit_params)

    if @profit.save
      redirect_to profits_path, notice: "Profit was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @profit.update(profit_params)
      redirect_to profits_path, notice: "Profit was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @profit.destroy
    flash.now[:notice] = 'Profit was successfully destroyed.'

    render turbo_stream: [
      turbo_stream.remove(@profit)
    ]
  end

  private
    def set_profit
      @profit = Profit.find(params[:id])
    end

    def profit_params
      params.require(:profit).permit(:amount, :daily_expences, :investment_funds,
                                    :funds_for_expensive_purchase, :funds_for_others,
                                    :funds_for_self_development, :savings, :user_id, :envelope_formula_id)
    end
end

app/views/profits/_form.html.erb
<%= simple_form_for(profit, html: { class: 'contents dark:text-gray-200 text-gray-700', data: { controller: 'envelope-formula' } }) do |f| %>
  <%= f.input :amount, input_html: {
                          class: 'text-gray-800',
                          data: {
                            envelope_formula_target: 'amount',
                            action: 'input->envelope-formula#calculate'
                          }
                        } %>
  <%= f.input :daily_expences, input_html: {
                                  class: 'text-gray-800',
                                  data: { envelope_formula_target: 'dailyExpences' }
                                } %>
  <%= f.input :savings, input_html: {
                          class: 'text-gray-800',
                          data: { envelope_formula_target: 'savings' }
                        } %>
  <%= f.input :funds_for_others, input_html: {
                                    class: 'text-gray-800',
                                    data: { envelope_formula_target: 'fundsForOthers' }
                                  } %>
  <%= f.input :funds_for_self_development, input_html: {
                                              class: 'text-gray-800',
                                              data: { envelope_formula_target: 'fundsForSelfDevelopment' }
                                            } %>
  <%= f.input :funds_for_expensive_purchase, input_html: {
                                                class: 'text-gray-800',
                                                data: { envelope_formula_target: 'fundsForExpensivePurchase' }
                                              } %>
  <%= f.input :investment_funds, input_html: {
                                    class: 'text-gray-800',
                                    data: { envelope_formula_target: 'investmentFunds' }
                                  } %>
  <%= f.association :envelope_formula, collection: options_with_data(EnvelopeFormula.ordered),
                                        input_html: {
                                          class: 'text-gray-800',
                                          data: {
                                            envelope_formula_target: 'formula',
                                            action: 'change->envelope-formula#calculate'
                                          }
                                        }, include_blank: false %>

  <%= f.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
<% end %>

app/views/profits/_profit.html.erb
<tr id="<%= dom_id(profit) %>" class="text-gray-700 dark:text-gray-400">
  <td class="px-4 py-3 text-xs"><%= profit.amount %></td>
  <td class="px-4 py-3 text-xs"><%= profit.daily_expences %></td>
  <td class="px-4 py-3 text-xs"><%= profit.savings %></td>
  <td class="px-4 py-3 text-xs"><%= profit.funds_for_others %></td>
  <td class="px-4 py-3 text-xs"><%= profit.funds_for_self_development %></td>
  <td class="px-4 py-3 text-xs"><%= profit.funds_for_expensive_purchase %></td>
  <td class="px-4 py-3 text-xs"><%= profit.investment_funds %></td>
  <td class="px-4 py-3 text-xs">
    <%= link_to edit_profit_path(profit), class: 'flex items-center w-fit justify-between px-2 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-full active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple', aria_label: 'edit' do %>
      <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
        <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path>
      </svg>
    <% end %>
  </td>
  <td class="px-4 py-3 text-xs text-red-500">
    <%= button_to profit_path(profit), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }  do %>
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
    <% end %>
  </td>
</tr>

app/views/profits/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-dark-grey dark:text-white">Editing profit</h1>

  <%= render "form", profit: @profit %>

  <%= link_to "Back to profits", profits_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/profits/index.html.erb
<section>
  <div class="flex flex-col justify-between gap-5 mb-5 sm:flex-row">
    <h1 class="text-4xl font-bold text-dark-grey dark:text-white">Profits</h1>
    <%= link_to 'New profit', new_profit_path, class: "btn-blue w-full sm:w-fit" %>
  </div>
  <div class="w-full overflow-hidden rounded-lg shadow-xs">
    <div class="w-full overflow-x-auto">
      <table class="w-full whitespace-no-wrap">
        <thead>
          <tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase bg-gray-100 border-b dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800">
            <th class="px-4 py-3">Amount</th>
            <th class="px-4 py-3">Daily expences</th>
            <th class="px-4 py-3">Savings</th>
            <th class="px-4 py-3">For others</th>
            <th class="px-4 py-3">For self development</th>
            <th class="px-4 py-3">For expensive purchase</th>
            <th class="px-4 py-3">Investment funds</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody id="envelope_formulas" class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
          <%= render @profits%>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/profits/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1>New profit</h1>

  <%= render "form", profit: @profit %>

  <%= link_to 'Back to profits', profits_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>